const { chromium } = require('playwright');
const path = require('path');
(async()=>{
  const browser = await chromium.launch({headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});
  const errors=[];
  page.on('console',m=>{if(m.type()==='error') errors.push(m.text())});
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto('file://'+path.resolve('index.html'));
  await page.waitForTimeout(800);
  await page.screenshot({path:'qa-queue.png',fullPage:true});
  const initial={screens:await page.locator('.screen').count(),rows:await page.locator('#caseRows tr').count(),open:await page.locator('#openMetric').textContent()};
  await page.click('[data-case="ir-2841"]');
  await page.click('[data-pane="consent"]');
  await page.click('[data-pane="history"]');
  await page.click('[data-pane="decision"]');
  await page.click('#approveMerge');
  await page.check('#confirmReview');
  await page.click('#confirmMerge');
  await page.waitForTimeout(300);
  const approved={status:await page.locator('#caseStatus').textContent(),open:await page.locator('#openMetric').textContent(),banner:await page.locator('#approvedBanner').isVisible()};
  await page.screenshot({path:'qa-case-approved.png',fullPage:true});
  await page.click('[data-screen="audit"]');
  const newestAudit=await page.locator('#auditRows tr').first().textContent();
  await page.screenshot({path:'qa-audit.png',fullPage:true});
  await page.click('[data-screen="onboarding"]');
  await page.screenshot({path:'qa-onboarding.png',fullPage:true});
  await page.click('[data-screen="analytics"]');
  await page.screenshot({path:'qa-operations.png',fullPage:true});
  console.log(JSON.stringify({title:await page.title(),initial,approved,newestAudit,errors},null,2));
  if(errors.length || initial.rows!==8 || !approved.banner || !newestAudit.includes('Merge approved')) process.exitCode=1;
  await browser.close();
})();
